name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: golang:1.23-alpine

    steps:
      - name: Install dependencies
        run: apk add --no-cache make

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install go dependencies
        run: go mod download

      - name: Run tidy
        run: make tidy

      - name: Run lint
        run: make lint

      - name: Build the project
        run: make build